doc/abrt-auto-reporting.txt, src/daemon/abrt-auto-reporting.c, tests/runtests/abrt-auto-reporting-sanity/runtest.sh
Requires: https://github.com/abrt/libreport/pull/309
=> RHEL7: auto-reporting: add options to specify auth type

src/plugins/ccpp_event.conf
=> Don't slurp unbounded amounts of data when invoking journalctl.

src/cli/abrt-console-notification.sh, tests/runtests/console-notifications/runtest.sh
=> Console notification timeout

tests/runtests/reporter-mantisbt/runtest.sh
=> updated tests to work with the new update of the repoter-mantisbt's searching methods

tests/runtests/reporter-mantisbt/runtest.sh
=> minor fix related to bug fix in libreport

abrt.spec.in, configure.ac, doc/abrt-action-save-package-data.txt, po/POTFILES.in, src/daemon/Makefile.am, src/daemon/abrt-action-save-container-data.c, src/daemon/abrt-action-save-package-data.c, src/daemon/abrt_event.conf, src/daemon/rpm.c, src/hooks/CCpp.conf, src/hooks/Makefile.am, src/hooks/abrt-hook-ccpp.c, src/hooks/abrt-install-ccpp-hook.in
Closes #885
Requires abrt/libreport#329
=> Start handling crashes in containers more effectively

src/hooks/CCpp.conf, src/plugins/abrt-action-install-debuginfo.in
=> ccpp: add support for multiple pkg mngrs

doc/problems-service/org.freedesktop.Problems.xml.in
=> doc: D-Bus api: make description of DeleteProblem clearer

src/plugins/abrt-dump-journal-oops.c, src/plugins/abrt-journal.c, src/plugins/abrt-journal.h, tests/runtests/journal-oops-processing/abrt_dump_oops_in_fake_root, tests/runtests/journal-oops-processing/runtest.sh
=> Enable reading systemd-journal files from an arbitrary directory

src/lib/kernel.c
=> lib: add new kernel taint flags

abrt.spec.in, configure.ac, po/POTFILES.in, src/daemon/abrt-action-save-package-data.c, src/daemon/abrt-server.c, src/daemon/abrt.conf, src/dbus/abrt-dbus.c, src/hooks/Makefile.am, src/hooks/abrt-hook-ccpp.c, src/include/libabrt.h, src/lib/abrt_conf.c, src/lib/hooklib.c, src/lib/problem_api.c, src/plugins/abrt-action-install-debuginfo-to-abrt-cache.c, src/plugins/abrt-dump-oops.c, src/plugins/abrt-dump-xorg.c, tests/Makefile.am, tests/hooklib.at, tests/testsuite.at
=> RHEL7: abrt ccpp vulnerabilities

tests/runtests/reporter-mantisbt/runtest.sh
=> don't run whole test if reporter-mantisbt isn't installed

src/applet/applet.c
Fix a double free problem.
Related to rhbz#1211644
=> applet: fix refcount problem info mechanism

abrt.spec.in, src/cli/list.c
=> abrt-cli add dependency on abrt-dbus

po/POTFILES.in, src/applet/applet.c, src/configuration-gui/abrt-config-widget.c, src/configuration-gui/abrt-config-widget.glade
=> GSettings integration

src/hooks/abrt-hook-ccpp.c, src/plugins/abrt-action-install-debuginfo-to-abrt-cache.c
* don't delete user core files
* don't open the build_ids file as the user abrt
=> WIP: RHEL7: missing fixes for the recent CVEs

abrt.spec.in
=> spec: remove analyzer to type conversion

Makefile.am, abrt.spec.in, configure.ac, src/hooks/Makefile.am
=> Optional atomic

abrt.spec.in, configure.ac, po/POTFILES.in, src/cli/abrt-cli-core.c, src/cli/abrt-cli-core.h, src/cli/report.c, src/daemon/abrt-action-save-package-data.c, src/daemon/abrt-server.c, src/daemon/abrt.conf, src/dbus/abrt-dbus.c, src/hooks/Makefile.am, src/hooks/abrt-hook-ccpp.c, src/include/libabrt.h, src/lib/abrt_conf.c, src/lib/hooklib.c, src/lib/problem_api.c, src/plugins/abrt-action-install-debuginfo-to-abrt-cache.c, src/plugins/abrt-dump-xorg.c, src/plugins/ccpp_event.conf, src/plugins/koops_event.conf, src/plugins/oops-utils.c, tests/Makefile.am, tests/hooklib.at, tests/testsuite.at
Requires: abrt/libreport#346
Requires: abrt/satyr#225
=> Ccpp vulnerabilities

src/plugins/ccpp_event.conf, tests/runtests/journald-integration/runtest.sh
Find more details about the dealing with system logs in #989
=> Do not save system logs by default

src/cli/abrt-cli.c, src/python-problem/doc/usage.rst, src/python-problem/problem/__init__.py, src/python-problem/problem/proxies.py, src/python-problem/problem/tools.py, src/python-problem/test, src/python-problem/tests/Makefile.am, src/python-problem/tests/test, src/python-problem/tests/test_properties.py
Few improvements and bugfixes. Related to new cli.
One unrelated cli commit removing dead code included.
=> Abrt python fixes

src/hooks/abrt_harvest_vmcore.py.in
=> vmcore: use libreport dd API in the harvestor

src/daemon/abrt_event.conf
=> sosreport: add processor information to sosreport

abrt.spec.in
=> spec: abrt requires libreport-plugin-rhtsupport on rhel

doc/abrt-cli.txt
=> doc: update abrt-cli man page

abrt.spec.in
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>
=> spec: use more appropriate url

tests/runtests/aux/test_order, tests/runtests/aux/test_order.rhel7, tests/runtests/ccpp-plugin-hook-unwind/PURPOSE, tests/runtests/ccpp-plugin-hook-unwind/runtest.sh
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>
=> testsuite: add ccpp-plugin-hook-unwind

tests/runtests/aux/lib.sh, tests/runtests/aux/test_order.rhel7, tests/runtests/distro_specific/rhel7/kernel-vmcore-harvest/PURPOSE, tests/runtests/distro_specific/rhel7/kernel-vmcore-harvest/runtest.sh, tests/runtests/distro_specific/rhel7/kernel-vmcore-harvest/vmcore-dmesg.txt
Dump directory has different rights and owner on RHEL7.
=> make kernel-vmcore-harvest distro specific

tests/runtests/journald-integration/runtest.sh
In the case, there are useless log messages the var_log_messages file is not
created in dump dir.
Related to rhbz#1255411
=> testsuite: useless var_log_messages files are not created

tests/runtests/dont-blame-interpret/runtest.sh
=> testsuite: improve logging in dont-blame-interpret test

tests/runtests/bz652338-removed-proc-PID/runtest.sh
=> testsuite: improve logging in bz652338-removed-proc-PID

tests/runtests/console-notifications/runtest.sh
There was introduced a new feature in commit [1], so the part "time out" of the
test "console-notifications" cannot work because abrt-cli doesn't wait until
the locked dump dir is unlocked.
[1] https://github.com/abrt/libreport/commit/77d29c3e533ec39a27c9c8bef3ba1e11983a2497
=> testsuite: fix console-notification test

tests/runtests/cli-sanity/runtest.sh
=> cli-sanity: comment 'not reportable' phase out

src/daemon/abrt_event.conf
File is not saved as current_config
=> events: fix example wording

tests/runtests/upload-filename/runtest.sh, tests/runtests/upload-ftp/runtest.sh, tests/runtests/upload-scp/runtest.sh, tests/runtests/ureport-attachments/pyserve, tests/runtests/ureport-attachments/runtest.sh
Use this pull request to test the libreport pull request:
https://github.com/abrt/libreport/pull/388
and merge this pull request together with it.
=> Test cases for QE workflow libreport changes

src/hooks/abrt-hook-ccpp.c, tests/runtests/aux/lib.sh, tests/runtests/ccpp-plugin/runtest.sh, tests/runtests/ccpp-plugin/will_segfault_locked_memory.c
=> C/C++: processes with locked memory

src/hooks/CCpp.conf, src/hooks/abrt-hook-ccpp.c, tests/runtests/aux/test_order, tests/runtests/ccpp-plugin-hook-ignoring/PURPOSE, tests/runtests/ccpp-plugin-hook-ignoring/runtest.sh
=> RHEL6: add IgnoredPath option

tests/runtests/event-configuration/test_Configuration.xml, tests/runtests/event-configuration/test_IncludesConfiguration.xml
They are present on master but not on rhel7 branch, causing this test to
fail all the time.
=> testsuite: event-configuration: add missing xml files

src/plugins/abrt-action-check-oops-for-hw-error.in
Fixes Red Hat Bugzilla Bug 1287302
The fix is the same kind as pull request https://github.com/abrt/abrt/pull/1099
=> a-a-c-o-f-hw-error: fix unicode error 2

src/hooks/abrt-hook-ccpp.c
Using executable name from core_pattern's parameter is not safe because in some
cases the core_pattern can contain bogus "executable name" parameter.
See
https://github.com/abrt/abrt/blob/master/src/hooks/abrt-install-ccpp-hook.in#L16
=> ccpp: use executable name from pid

src/plugins/abrt-dump-journal-xorg.c
=> Fix minor typo: possition -> position

src/plugins/abrt-action-install-debuginfo.in
=> BrokenPipe error fix

doc/abrt-CCpp.conf.txt, src/hooks/CCpp.conf, src/hooks/abrt-hook-ccpp.c, src/include/hooklib.h, src/lib/hooklib.c, tests/runtests/aux/test_order, tests/runtests/ccpp-plugin-hook-ignoring/PURPOSE, tests/runtests/ccpp-plugin-hook-ignoring/runtest.sh
Related to rhbz#1277849 rhbz#1277848
Requires https://github.com/abrt/libreport/pull/418
=> RHEL7: abrt-hook-ccpp: add user whitelisting and executable path blacklisting

src/daemon/abrt-server.c, tests/runtests/abrtd-infinite-event-loop/PURPOSE, tests/runtests/abrtd-infinite-event-loop/runtest.sh, tests/runtests/aux/test_order
Require: https://github.com/abrt/libreport/pull/431
=> Try to avoid infinite post-mortem processing loops

src/plugins/vmcore_event.conf, tests/runtests/kernel-vmcore-harvest/runtest.sh
=> RHEL7: Generate 'reason' file from dmesg log file 

src/cli/abrt-console-notification.sh
Related to #898 
Resolves: rhbz#1249101
=> RHEL7: console-notifications: add timeout

src/hooks/abrt_exception_handler.py.in, tests/runtests/python-addon/runtest.sh
=> RHEL7: fix RequireAbsolutePath from /etc/abrt/plugins/python.conf

doc/abrt-CCpp.conf.txt, src/hooks/CCpp.conf
=> Improve documentation of AllowedGroups, AllowedUsers and IgnoredPaths

src/plugins/xorg-utils.c, src/plugins/xorg.conf
=> Improve extracting of xorg crashes from journal

configure.ac, src/hooks/Makefile.am, src/hooks/abrt_harvest_vmcore.py.in
findmnt solves both problems:
* UUID=/LABEL=
* different device links
Related: rhbz#1147053
=> Ultimately fix the problems with finding moutpoint in the vmcore harvestor

src/hooks/abrt-hook-ccpp.c
Kernel sets RLIMI_CORE to 1 for core_pattern processes in order to avoid
crash recursion. Thus if we want to be able to dump own corefile, we
must set RLIMIT_CORE !=1.
In order to avoid unintended disasters cause by crash recursion, the
core file will be produced only if DebugLevel is >= 100. This
should ensure that we can debug abrt problems without infinite recursion
in abrt-hook-ccpp.
SELinux prevents abrt-hook-ccpp from changing its own RLIMIT_CORE,
therefore, SELinux must be in permissive mode at least. Otherwise, the
core file won't be produced as RLIMIT_CORE will remain set to 1.
=> hook-ccpp: dump own core file in debug mode

src/daemon/abrt-handle-event.c, src/daemon/abrt-server.c, src/daemon/abrtd.c
Covered by the abrtd-concurrent-processing test.
=> Abrtd concurrent processing

src/hooks/abrt_harvest_vmcore.py.in
=> Teach abrt-harvest-vmcore to parse kdump.conf at any path

abrt.spec.in, src/hooks/Makefile.am, src/hooks/abrt-hook-ccpp.c, tests/runtests/ccpp-plugin-hook-unwind/root_to_unprivileged.c, tests/runtests/ccpp-plugin-hook-unwind/runtest.sh, tests/runtests/ccpp-plugin-hook-unwind/unprivileged_to_root.c, tests/runtests/ccpp-plugin-hook-unwind/verify_core_backtrace.py
Requires https://github.com/abrt/satyr/pull/251
=> Run elfutils under an unprivileged user

src/daemon/abrt-server.c, src/hooks/abrt-hook-ccpp.c
While playing with my box I noticed several problems.
=> Fixes and improvements

doc/problems-service/org.freedesktop.Problems.xml.in
=> problems2: update the documentation

tests/runtests/abrtd-infinite-event-loop/runtest.sh
=> testsuite: a-i-event-loop - sleep to avoid race cond

doc/abrt-cli.txt, src/cli/builtin-cmd.h, src/cli/process.c, src/cli/report.c, src/lib/abrt_glib.c, tests/runtests/aux/test_order, tests/runtests/cli-process/PURPOSE, tests/runtests/cli-process/expect, tests/runtests/cli-process/runtest.sh
The pull request needs https://github.com/abrt/libreport/pull/475
Related to #1257159
=> RHEL7: abrt-cli allows to start reporting not-reportable problems

tests/runtests/cli-sanity/runtest.sh
=> tests - cli-sanity: re-enable report non-reportable phase

src/include/libabrt.h, src/lib/kernel.c, src/plugins/abrt-dump-journal-oops.c, src/plugins/abrt-dump-journal-xorg.c, src/plugins/abrt-journal.c, src/plugins/abrt-journal.h, tests/Makefile.am, tests/examples/debug_messages.right, tests/examples/debug_messages.test, tests/koops-parser.at
resolves problem with DEBUG messages considered as BUGs in kernel log.
added koops suspicious string blacklist, with one entry yet - "DEBUG"
added test
=> Fix 1444924

doc/abrt.conf.txt
=> This fixes #1173

src/applet/applet.c
=> applet: add a default action to a notification

src/plugins/abrt-action-ureport
Requires https://github.com/abrt/libreport/pull/503
=> Allow sending uReports for crashes from unpackged executables

src/daemon/rpm.c
Signed-off-by: mhabrnal <mhabrnal@localhost.localdomain>
=> rpm: include epocho in package element if > 0

src/daemon/abrt-handle-event.c, tests/runtests/docker-essentials/runtest.sh
Related to #1270 
This is the simplest solution. I do **not** insist on merging this PR. It is more like  _conversation starter_, so we can find the best solution.
This keeps the whole dumpdir event when the same crash happened in two different containers. But it deduplicates the same problem from one container.
There are many options, how to improve this, but in each and every of theme  is some catch, that is way to complex to solve.
Options @jfilak @mhabrnal @xsuchy ?
=> Duplicate container crashes

src/daemon/abrt-action-save-container-data.c, src/plugins/bodhi.c
Signed-off-by: Matej Marusak <mmarusak@redhat.com>
=> Remove deprecated is_error macro

abrt.spec.in, src/hooks/Makefile.am, src/hooks/abrt3_container.pth, src/hooks/abrt_exception_handler3_container.py, src/plugins/Makefile.am, src/plugins/abrt-container-logger.c
More info in blog post: https://abrt.github.io/openshift/abrt/python/docker/2018/02/08/abrt-for-docker/
=> Introduce a new tool for Catching unhandled Python exception in Docker

src/plugins/abrt-retrace-client.c, src/plugins/abrt-watch-log.c
vfork is insecure as it can lead to denial of service situations in the parent process[1].
[1] https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152373
resolves #1311
=> plugins: Replace vfork with posix_spawn

abrt.spec.in, src/plugins/sosreport_event.conf
=> sosreport: plugin "general" split into two new plugins

.gitignore, src/plugins/abrt-action-check-oops-for-hw-error.in, tests/examples/oops-non-fatal-mce.test.template, tests/runtests/non-fatal-mce/runtest.sh
Adds systemd-journal to places to check for MCE logs.
Related: rhbz#1496303
=> Check systemd-journal for MCE logs

src/lib/hooklib.c
Signed-off-by: Steven Walter <swalter@lexmark.com>
Signed-off-by: Kyle Russell <kyle.russell@lexmark.com>
=> signal_is_fatal: generate problem reports for SIGSYS

pylintrc
Signed-off-by: Matej Marusak <mmarusak@redhat.com>
=> Introduce pylintrc

tests/runtests/aux/test_order.rhel8, tests/runtests/dumpdir_completedness/runtest.sh, tests/runtests/rhts-test/pyserve
=> More test madness

src/dbus/abrt_problems2_task.c, src/dbus/abrt_problems2_task.h
=> dbus: task: Use modern GLib type macros

src/plugins/abrt-action-find-bodhi-update
=> a-a-find-bodhi-update: Do not crash with nonexistent dir

abrt.spec.in
References: https://fedoraproject.org/wiki/Changes/RemoveObsoleteScriptlets
(cherry-picked from https://src.fedoraproject.org/rpms/abrt/c/eadff202bca229eecaaceefecfb83cffa878074e?branch=master)
Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>
=> spec: Remove obsolete scriptlets

tests/runtests/dbus-argument-validation/runtest.sh
=> testsuite: Look for abrt-dbus identifier in logs

src/daemon/abrt-upload-watch.c, src/daemon/abrtd.c
=> daemon: Check return value after reading from channel

src/daemon/abrt-action-save-package-data.conf
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1693282
=> daemon: Don't process crashes from unpackaged apps by default

src/plugins/abrt-action-install-debuginfo.in
https://bugzilla.redhat.com/show_bug.cgi?id=1501178
Tried my best to split things up, but it only goes so far.
=> Shuffle things around and hopefully avoid BrokenPipeErrors for good

abrt.spec.in
Time to get rid of these.
Introduced in ab4c89a
=> spec: Revisit old Python provides

tests/runtests/skip-sosreport-dir/runtest.sh
Related to:
https://github.com/abrt/libreport/pull/571
=> testsuite: Add test for skipping sosreport dirs

src/cli/abrt
See commits.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1770034
=> cli: Print usage if non-action option passed without a command

src/configuration-gui/abrt-config-widget.c, src/dbus/abrt_problems2_service.c, src/dbus/abrt_problems2_service.h, src/dbus/abrt_problems2_session.c, src/dbus/abrt_problems2_task.c, src/plugins/oops-utils.c, src/plugins/oops-utils.h, src/plugins/xorg-utils.c, src/plugins/xorg-utils.h
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1795820
Signed-off-by: Michal Fabik mfabik@redhat.com
=> Fix build failure with gcc -fno-common

tests/runtests/mailx-reporting/formatting_files/mailx_format_attach.conf.right, tests/runtests/mailx-reporting/runtest.sh, tests/runtests/reporter-systemd-journal/runtest.sh
Several integration tests are failing for various reasons.
=> WIP: Fix for failing integration tests

src/lib/kernel.c, src/plugins/abrt-action-analyze-oops.c
The current code that sets up hostname needles for searching the oops
haystack is a bit blegh. This commit simplifies it.
=> Small refactorings

src/cli/abrt, src/cli/abrtcli/cli/__init__.py
=> Smol CLI tweaks/fixes

src/plugins/xorg-utils.c
Why don’t you take a seat and… see commits.
=> Xorg-related code shuffling

src/applet/abrt-applet-application.c, src/applet/abrt-applet-problem-info.c, src/applet/abrt-applet-problem-info.h, src/plugins/abrt-action-notify
=> applet: Refactor code

src/daemon/abrt-auto-reporting.c
Leftover from https://github.com/abrt/abrt/pull/1467
Resolves:
https://github.com/abrt/abrt/issues/1483
=> auto-reporting: Fix missing libreport_ namespace

src/applet/abrt-applet-application.c
See commits.
https://bugzilla.redhat.com/show_bug.cgi?id=1836190
=> Fix applet segfault again

src/cli/abrt-console-notification.sh
See commits.
Fixes https://github.com/abrt/abrt/issues/1371
=> abrt-console-notification: prevent noclobber from spoiling the fun

src/daemon/rpm.c, src/dbus/abrt_problems2_service.c, src/plugins/abrt-dump-journal-core.c, src/plugins/abrt-retrace-client.c, src/plugins/oops-utils.c
=> Fix defects found by Coverity

src/dbus/abrt_problems2_service.c, src/python-problem/problem/watch.py
See commits. The other commit should also take care of things like https://bugzilla.redhat.com/show_bug.cgi?id=1740076.
=> python-problem: Use the new D-Bus interface for watching

src/daemon/abrt-server.c, src/daemon/abrtd.c, src/daemon/rpm.c, src/dbus/abrt-dbus.c, src/dbus/abrt_problems2_service.c, src/lib/kernel.c, src/plugins/abrt-action-trim-files.c, src/plugins/abrt-dump-oops.c, src/plugins/bodhi.c
* Decommission `libreport_list_free_with_free()` -- follow-up to abrt/libreport#660
* Purge commented-out code.
=> Minor code clean up

abrt.spec.in
=> Spec tweaks

CHANGELOG.md, CONTRIBUTING.md
To make pre-release chores easier.
=> CHANGELOG: Update with PR 1537

abrt.spec.in
Resolves:
https://github.com/abrt/abrt/issues/1519
=> spec: Don't use GitHub-generated tarball as Source

doc/abrt-action-analyze-vulnerability.txt
Add more infromation about the tool and exploitable rating
in general.
Related:
https://github.com/abrt/abrt/issues/665
=> Doc: Improve man page for abrt-action-analyze-vulnerability

src/plugins/abrt-retrace-client.c, tests/xorg-utils.at
Fix a couple of minor issues that were causing `make rpm` to fail.  
See commits.
=> Make rpm fix

.gitignore, CHANGELOG.md, configure.ac, m4/ld-version-script.m4, src/configuration-gui/Makefile.am, src/configuration-gui/libabrt_gui.sym, src/lib/Makefile.am, src/lib/libabrt.sym
Add version info script for liabrt and libart_gui.
Fixes:
https://github.com/abrt/abrt/issues/603
Nore: We will still have soname 0.0.1 until next release (we will bump the version for every release).
=> libs: Add version info script

.git-commit-template, CONTRIBUTING.md
See commit. Like in the other projects.
=> Add commit message template

src/daemon/rpm.c
Added support of master + subkeys gpg.
=> Fixed rpm_load_gpgkey.

src/plugins/abrt-action-find-bodhi-update
* Port to standard library `logging` module.
* Fix control flow in edge cases.
* Factor out some code.
* Make variables names more readable.
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1970921
=> a-a-find-bodhi-update: Refactoring

README.md
We have migrated from Freenode to Libera Chat
=> readme: Update IRC channel

abrt.spec
This is Fedora compatible.
Not sure what operating systems this spec file supports.
Cherry-picked from https://src.fedoraproject.org/rpms/abrt/pull-request/16
=> Fix issues with conflicting multilib packages

src/daemon/abrt-action-save-package-data.c, src/daemon/abrt-auto-reporting.c, src/daemon/abrt-server.c, src/lib/abrt_conf.c, src/plugins/abrt-retrace-client.c, src/plugins/bodhi.c
Fix a couple of memory management-related (potential) bugs found by Covscan.
=> Fix potential memory management bugs

src/applet/abrt-applet-application.c, src/daemon/abrt-upload-watch.c, src/lib/hooklib.c, src/lib/migrate_dirs.c, src/plugins/abrt-action-install-debuginfo-to-abrt-cache.c, src/plugins/abrt-retrace-client.c, src/plugins/abrt-watch-log.c
Check return values of various library functions and emit errors or warnings on failure.
=> Check return values

doc/abrt-bodhi.txt
=> [man] Update man page for abrt-bodhi

abrt.spec
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
=> use SPDX format for license

src/daemon/abrtd.c, src/dbus/abrt-dbus.c
=> Fix integer overflow for MaxCrashReportsSize

init-scripts/abrtd.service
Taken from https://src.fedoraproject.org/rpms/abrt/pull-request/32#
Thanks to Tim Lawrence for the patch ;)
=> Update systemd settings
