src/daemon/abrt-handle-upload.in
src/hooks/abrt-harvest-pstoreoops.in
src/hooks/abrt_harvest_vmcore.py.in
src/plugins/abrt-action-analyze-core.in
src/plugins/abrt-action-analyze-vmcore.in
src/plugins/abrt-action-generate-machine-id
src/plugins/abrt-action-install-debuginfo.in
src/plugins/abrt-action-list-dsos
src/plugins/abrt-action-perform-ccpp-analysis.in
src/plugins/abrt-action-ureport

This patch just applies what 2to3 found so that the scripts can run both
under python 2 and python 3. More work is needed to fully switch to
python 3.
Related to rhbz#1192080.
Signed-off-by: Martin Milata <mmilata@redhat.com>

Python 3 compatibility

---

src/plugins/abrt-action-analyze-core.in
src/plugins/abrt-action-list-dsos

Fixes two places where `bytes` are used instead `unicode` in python3 (or vice versa?).
With this patch + shebangs replaced with `#!/usr/bin/python3` the basic functionality of ABRT seems to work under Fedora 22. Dependencies in spec file will have to be adujsted as well for the migration (e.g. add `rpm-python3` and `python3-augeas` (currently only in F22)).

Python 3 fixes

---

src/applet/applet.c
src/include/libabrt.h
src/lib/problem_api_dbus.c

This patch is a part of our efforts to make abrt-applet independent on
the backend.
This patch converts all data manipulation functions to D-Bus calls, so
the notifications are made of data obtained through D-Bus.
The reporting still relies on file system access, though.

Port the applet to D-Bus methods

---

src/daemon/abrt-handle-upload.in

It was discovered that, when moving problem reports from
/var/spool/abrt-upload to /var/spool/abrt or /var/tmp/abrt,
abrt-handle-upload does not verify that the new problem directory
has appropriate permissions and does not contain symbolic links.  A
crafted problem report exposes other parts of abrt to attack, and
the abrt-handle-upload script allows to overwrite arbitrary files.
Acknowledgement:
This issue was discovered by Florian Weimer of Red Hat Product Security.
Related: #1212953

RHEL7: upload: validate and sanitize uploaded dump directories

---

src/daemon/abrt-handle-upload.in

It was discovered that, when moving problem reports from
/var/spool/abrt-upload to /var/spool/abrt or /var/tmp/abrt,
abrt-handle-upload does not verify that the new problem directory
has appropriate permissions and does not contain symbolic links.  A
crafted problem report exposes other parts of abrt to attack, and
the abrt-handle-upload script allows to overwrite arbitrary files.
Acknowledgement:
This issue was discovered by Florian Weimer of Red Hat Product Security.
Related: #1212953

upload: validate and sanitize uploaded dump directories

---

src/daemon/abrt-action-save-package-data.conf

There were new bugzillas opened with wrong component 'python3' because of a new
version of python (3.4). We don't want to blame the interpreters but the
running scripts.
close #965

a-a-s-p-d: add new known interpreter to conf file

---

src/plugins/abrt-action-list-dsos

In case there are installed some dirty packages the abrt-action-list-dsos failed.

abrt-action-list-dsos: dirty packages don't have a RPMTAG_VENDOR item

---

tests/runtests/abrt-auto-reporting-sanity-authenticated/PURPOSE
tests/runtests/abrt-auto-reporting-sanity-authenticated/runtest.sh
tests/runtests/abrt-auto-reporting-sanity/runtest.sh
tests/runtests/aux/test_order.rhel6
tests/runtests/aux/test_order.rhel7

The first part tests abrt-auto-reporting sanity which not contains an
authenticated options. This part is the same for fedora and rhel and runs on both.
The second one tests options for authenticated reporting and the test runs only
on rhel.
Related to rhbz#1223822

testsuite: add authenticated autoreporting by certificate test

---

src/hooks/abrt-hook-ccpp.c
src/plugins/abrt-action-analyze-backtrace.c

Save TID and use it do get the crash thread. Requires: abrt/libreport#369

C/C++: Thread ID

---

abrt.spec.in

Signed-off-by: Richard Marko <rmarko@fedoraproject.org>

spec: --enable-dump-time-unwind by default

---

examples/10_oopses.test
examples/1_oops.test
examples/no_oops.test
src/plugins/abrt-dump-oops.c
tests/runtests/aux/test_order
tests/runtests/oops-sanity/PURPOSE
tests/runtests/oops-sanity/runtest.sh

In case that found more than one oops process the first one.
Without this patch the script exits with error in this case because expects
only one oops.
Related to rhbz#1170534

a-dump-oops: allow update the problem, if more then one oops found

---

doc/abrtd.txt
src/daemon/abrt-handle-event.c
src/daemon/abrt-server.c

The crash processing should not make the computer unusable. It sometimes
happens that the captured data causes abrt scripts to take an inadequate
amount of resources and the computer becomes less responsive.
This patch increases the nice value of post-create processes by 10 (I took
10 because it is the default value of command 'nice'), so those
processes will be scheduled after the more valuable processes.
Related: rhbz#1236422

abrtd: de-prioritize post-create event scripts

---

src/daemon/abrt-handle-upload.in
src/plugins/abrt-action-analyze-core.in
src/plugins/abrt-action-analyze-vmcore.in
src/plugins/abrt-action-check-oops-for-alt-component.in
src/plugins/abrt-action-check-oops-for-hw-error.in
src/plugins/abrt-action-install-debuginfo.in
src/plugins/abrt-action-perform-ccpp-analysis.in
src/plugins/abrt-action-ureport
src/plugins/abrt-gdb-exploitable

lgettext returns bytes but we require string.
Without this patch the scripts exit with 'TypeError' exception ('must be str,
not bytes').
Related to rhbz#1245600

use gettext instead of lgettext in all python scripts

---

src/daemon/Makefile.am

We discovered that conditional compilation in abrt-auto-reporting does not
work. We forgot add -DAUTHENTICATED_AUTOREPORTING=1 flag if
AUTHENTICATED_AUTOREPORTING is enabled.
Related to rhbz#1191572

abrt-auto-reporting: fix related to conditional compilation

---

doc/Makefile.am

abrt-auto-reporting.txt is a copy of either
abrt-auto-reporting-authenticated.txt or
abrt-auto-reporting-unauthenticated.txt. abrt-auto-reporting.txt file always
exists so we must do an enforce copy to get the right version of man page.
Related to rhbz#1191572

doc: fix related to conditional compilation of man page

---

tests/runtests/aux/test_order.rhel7
tests/runtests/distro_specific/rhel7/oops-processing/PURPOSE
tests/runtests/distro_specific/rhel7/oops-processing/runtest.sh

There is no "DropNotReportableOopses" option in oops.conf on rhel, so we remove
the test cases related to this.

testsuite: make oops-processing distro specific

---

tests/runtests/aux/test_order.rhel7
tests/runtests/distro_specific/rhel7/journald-integration/PURPOSE
tests/runtests/distro_specific/rhel7/journald-integration/morituri.c
tests/runtests/distro_specific/rhel7/journald-integration/runtest.sh

System logs are stored on RHEL. Don't save the system logs by default was
introduced in commit
https://github.com/abrt/abrt/commit/fbea8811e93bed6c8fe665b47feeb9bd1cc7b755.

testsuite: make journald-integration test distro specific

---

tests/runtests/dbus-configuration/runtest.sh

There are different default values in abrt-action-save-package-data.conf
(option "Interpreters" and "ProcessUnpackaged" on RHEL and on Fedora. The test
failed because the value for the options are written in the test so it works
only on Fedora. The patch adds reading the option values straight from conf file.

testsuite: dbus-configuration: read option values from conf file

---

doc/abrt-CCpp.conf.txt
src/hooks/CCpp.conf

The comment fits only on the default core_pattern template.
If the core_pattern is not default, the comment does not fit.
Related to rhbz#1252384

ccpp: fix comment related to 'MakeCompatCore' option in CCpp.conf

---

tests/runtests/abrt-auto-reporting-sanity/runtest.sh

phase "missing rhtsupport.conf" is not relevant for RHEL

testsuite: abrt-auto-reporting-sanity - exclude one phase on RHEL

---

src/daemon/abrt-action-save-package-data.conf

In case of this package, the reported data doesn't yield sufficient information
to solve a bug.
Related to rhbz#1250379

a-a-s-p-d: add bash on the package blacklist

---

tests/runtests/dbus-elements-handling/runtest.sh

Dump directories are owned by root now (introdiced in commit
https://github.com/abrt/abrt/commit/8939398b82006ba1fec4ed491339fc075f43fc7c).
Due to this changes the test began to fail. We want to regular users to
own the problem data colleted by abrt in the dbus-element-handling test.
To ensure this, we must set the 'PrivateReports' option to 'no' in abrt.conf.
The 'PrivateReports' option is only on RHEL.

testsuite: d-e-handling set 'PrivateReports' to 'no' in abrt.conf

---

tests/runtests/oops-processing/runtest.sh

There was introduced a new feature [1], so this commit fixes those changes in
this testsuite.
[1] https://github.com/abrt/abrt/commit/4905fcc0e6c2c16fa3d28eeeabe5bd440a1b1a05

testsuite: fix test oops_processing

---

doc/abrt-bodhi.txt

Parameters -d and -u were not in the man page.

doc: actualize the abrt-bodhi man page

---

tests/runtests/bugzilla-bt-reattach/bugzilla.conf
tests/runtests/bugzilla-comment-format/bugzilla.conf
tests/runtests/bugzilla-dupe-search/bugzilla.conf

With the recent bugzilla update, new more strict password rules are enforced. The testing account pw has been changed, thus the tests need to use it.

runtests: stick to new BZ password rules

---

tests/runtests/aux/pre.sh

dnf dependens on libreport-filesystem
and uninstall itself when trying to remove libreport-filesystem.
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>

testsuite: use rpm to remove packages

---

tests/runtests/ureport-auth/runtest.sh

When running the test by hand, the configuration doesn't get restored properly. This simple patch makes restoring more robust.

testsuite: ureport-auth: force cp/mv when restoring configuration

---

tests/runtests/aux/lib.sh

Sometimes get_crash_path fails mysteriously. Adding some debugging output directly in the test log won't hurt.

runtests: more verbose fail in get_crash_path

---

src/plugins/abrt-dump-xorg.c
tests/runtests/dumpxorg/crash_bz1264739.right
tests/runtests/dumpxorg/crash_bz1264739.test

The backtraces looks like
[ 60244.259] (EE) Backtrace
[ 60244.262] (EE) 0: /usr/libexec/Xorg (OsLookupColor+0x139) [0x59add9]
[ 60244.264] (EE) 1: /lib64/libc.so.6 (__restore_rt+0x0) [0x7f61be425b1f]
...
[ 60244.273] (EE) 13: ? (?+0x29) [0x29]
[ 60244.273] (EE)
[ 60244.273] (EE) Segmentation fault at address 0x7f61d93f6160
This format of Xorg log files was not supported by abrt-dump-xorg tool.
Related to rhbz#1264739

abrt-dump-xorg: support Xorg log backtraces prefixed by (EE)

---

src/plugins/abrt-retrace-client.c

Otherwise we get
The size of your crash is 28.1 MiB, but the retrace server only accepts
crashes smaller or equal to 16.0 EiB.
(gdb) print settings->max_unpacked_size
$4 = -50331648

abrt-retrace-client: use atoll for _size conversion

---

src/daemon/abrt-handle-event.c
src/lib/problem_api.c

If the code is not needed then it might be a good idea
to actually get rid of it instead of adding a
notice that it is not needed...
Also fixes variable naming that saved stunning one character!

remove 'not needed' code

---

abrt.spec.in
doc/Makefile.am
doc/abrt-action-find-bodhi-update.txt
po/POTFILES.in
src/plugins/Makefile.am
src/plugins/abrt-action-analyze-ccpp-local.in
src/plugins/abrt-action-find-bodhi-update
src/plugins/ccpp_retrace_event.conf
tests/runtests/abrt-action-find-bodhi-update/PURPOSE
tests/runtests/abrt-action-find-bodhi-update/runtest.sh
tests/runtests/aux/test_order
tests/runtests/bugzilla-dupe-search/runtest.sh

The tool 'abrt-action-search-bodhi-updates' takes one parameter DUMP_DIR path,
reads duphash file in problem directory and searches for a new updates
according to the crash using abrt-bodhi client.
Related to rhbz#1268218

bodhi: introduce wrapper for 'reporter-bugzilla -h' and 'abrt-bodhi'

---

tests/runtests/upload-handling/runtest.sh

using cp instead of mv ensures the tarball to have proper SELinux context

testsuite: upload-handling: fix irrelevant AVCs

---

abrt.spec.in
doc/Makefile.am
doc/abrt-dump-journal-core.txt
src/plugins/abrt-dump-journal-core.c
tests/runtests/abrt-dump-journal-core/PURPOSE
tests/runtests/abrt-dump-journal-core/runtest.sh
tests/runtests/aux/test_order

Without this commit abrt-server fails during check the right owner and group of
dump dirs.
Related to rhbz#1269827

a-d-journal-core: set root owner for created dump directory

---

abrt.spec.in
doc/Makefile.am
doc/abrt-action-analyze-xorg.txt
doc/abrt-dump-journal-xorg.txt
examples/xorg_journal_crash1.right
examples/xorg_journal_crash1.test
examples/xorg_journal_crash2.right
examples/xorg_journal_crash2.test
init-scripts/abrt-xorg.service
po/POTFILES.in
src/plugins/Makefile.am
src/plugins/abrt-dump-journal-core.c
src/plugins/abrt-dump-journal-oops.c
src/plugins/abrt-dump-journal-xorg.c
src/plugins/abrt-dump-xorg.c
src/plugins/abrt-journal.c
src/plugins/abrt-journal.h
src/plugins/xorg-utils.c
src/plugins/xorg-utils.h
src/plugins/xorg.conf
tests/Makefile.am
tests/atlocal.in
tests/local.at
tests/runtests/aux/test_order
tests/runtests/journal-xorg-crash-processing/PURPOSE
tests/runtests/journal-xorg-crash-processing/runtest.sh
tests/testsuite.at
tests/xorg-utils.at

Resolves abrt/abrt#1023
Related to rhbz#1246373

Introduce tool abrt-dump-journal-xorg

---

tests/runtests/rhts-test/runtest.sh

RHTS changed URL of the attachments, causing this test to fail.

testsuite: rhts-test: fix for modified rs API

---

tests/runtests/ccpp-plugin-debug/runtest.sh

testsuite: ccpp-plugin-debug: normalize ABRT_BINARY_COREDUMP

---

doc/abrt-CCpp.conf.txt
src/daemon/abrt-server.c
src/hooks/CCpp.conf
src/hooks/abrt-hook-ccpp.c
src/lib/check_recent_crash_file.c
tests/runtests/aux/test_order
tests/runtests/ccpp-plugin-hook-ignoring/PURPOSE
tests/runtests/ccpp-plugin-hook-ignoring/failing_code.c
tests/runtests/ccpp-plugin-hook-ignoring/runtest.sh

ABRT will ignore crashes in executables whose absolute path matches one of
specified patterns.
Related to rhbz#1208713

add BlackListedPaths option to abrt-hook-ccpp

---

po/tr.po

mnowak> jfilak, then it fails with:
mnowak> rm -f tr.gmo && /usr/bin/msgfmt -c --statistics -o tr.gmo tr.po
mnowak> tr.po:14: warning: header field 'Project-Id-Version' still has the initial default value
mnowak> tr.po:1594: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
mnowak> 91 translated messages, 8 fuzzy translations, 346 untranslated messages.
mnowak> Makefile:200: recipe for target 'tr.gmo' failed
jfilak> mnowak: oops, I'll look into this tomorrow. I need to go now. Sorry.

Use %s instead of %d.

---

src/plugins/abrt-action-check-oops-for-hw-error.in

Fixes Red Hat Bugzilla Bug 1287302
Signed-off-by: Jan Beran <jberan@redhat.com>

a-a-c-o-f-hw-error: do not crash on invalid unicode

---

doc/abrt-CCpp.conf.txt
doc/abrt.conf.txt
src/hooks/CCpp.conf
src/hooks/abrt-hook-ccpp.c
tests/runtests/ccpp-plugin-hook-ignoring/runtest.sh

The feature allows dump core only for allowed users.
The logic is the following:
- if both options are not-defined or empty keep all core dumps
- else if crashed UID is in the list of users keep the core dump
- else if crashed UID belongs to a group in the list of groups keep the core dump
Related to rhbz#1256705
**Requires:** https://github.com/abrt/libreport/pull/398

 ccpp: add AllowedUsers and AllowedGroups feature

---

src/hooks/CCpp.conf
src/hooks/abrt-hook-ccpp.c
tests/runtests/ccpp-plugin-hook-ignoring/runtest.sh

The feature allows dump core only for allowed users.
The logic is the following:
- if both options are not-defined or empty keep all core dumps
- else if crashed UID is in the list of users keep the core dump
- else if crashed UID belongs to a group in the list of groups keep the core dump
Related to rhbz#1256705
Requires: https://github.com/abrt/libreport/pull/400

RHEL6: ccpp: add AllowedUsers and AllowedGroups feature

---

src/daemon/abrt-action-save-package-data.conf

/usr/lib(64)/firefox/plugin-container is a sandbox/launcher for Firefox
plug-ins. When it crases Firefox loads it again so we don't want those crashes
reported.
Related to: rhbz#1308840

a-a-save-package-data: blacklist /usr/lib(64)/firefox/plugin-container

---

augeas/abrt.aug

Without this commit it was not possible to seve
/files/etc/abrt/plugins/oops.conf/DropNotReportableOopses.
Related to rhbz#1175679
- thanks to Dominic Cleal for the patch

RHEL7: augeas: augtool save oops.conf/DropNotReportableOopses

---

src/hooks/abrt_harvest_vmcore.py.in

Perhaps some temporary data cleaner removed problem directory while the hook
was still using in.
Resolves: rhbz#1077241

RHEL7: vmcore: catch IOErrors and OSErrors

---

tests/runtests/aux/config.sh
tests/runtests/aux/runner.sh

Regardless it is a bug in a test if the test hangs, we need to be able
to recover from this unpleasant state. One test must not destroy entire
suite.
I have chosen 15 minutes without any empirical measurements and I
believe that value is good for us.

testsuite: add a per test timeout for 15m

---

tests/runtests/rhts-test/pyserve
tests/runtests/rhts-test/runtest.sh

testsuite: reporter-rhtsupport should attach whole dumpdir to a case

---

tests/runtests/aux/test_order
tests/runtests/mailx-dead-letter/PURPOSE
tests/runtests/mailx-dead-letter/mailx.conf
tests/runtests/mailx-dead-letter/runtest.sh

testsuite: mailx does not create dead.letter in failure

---

tests/runtests/aux/test_order
tests/runtests/mailx-dead-letter/PURPOSE
tests/runtests/mailx-dead-letter/mailx.conf
tests/runtests/mailx-dead-letter/runtest.sh

RHEL7: testsuite: mailx does not create dead.letter in failure

---

src/lib/hooklib.c

In the case an uid element doesn't exist in time of dump dir creating, we have
to create dump dir owned by root.
Related to rhbz#1264921

RHEL7: lib: prevent from creating non-root sub-dirs in dump dir

---

src/dbus/abrt-dbus.c
src/dbus/abrt-polkit.c
src/lib/abrt_conf.c
src/lib/abrt_glib.c
src/lib/problem_api.c

Fix several repeated leaks that were causing abrt-dbus to waste system
memory.
I used this valgrind command:
valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all \
--track-origins=yes --suppressions=glib.supp \
--log-file=/tmp/leaks-$(date +%s).txt abrt-dbus -vvv -t 10
With suppressions from libsecret and NetworkManager:
* https://raw.githubusercontent.com/GNOME/libsecret/master/build/glib.supp
* https://raw.githubusercontent.com/NetworkManager/NetworkManager/master/valgrind.suppressions
The suppressions were needed because Glib allocates a lot of static
stuff and does not free it at exit because it is useless.
Resolves: #1319704

RHEL7: Fix memory leaks in abrt-dbus

---

src/hooks/CCpp.conf
src/plugins/abrt-action-install-debuginfo.in

a-a-install-debuginfo: correct handling of DebuginfoLocation

---

tests/runtests/python-addon/runtest.sh
tests/runtests/python3-addon/runtest.sh

The option is placed in '/etc/abrt/plugins/python.conf' and
the option is placed in '/etc/abrt/plugins/python3.conf'.

testsuite: add test for RequireAbsolutePath option

---

src/plugins/abrt-action-install-debuginfo.in

Bug introduced in commit bb653b71a9261c0b58a9256761bf034b24c2e1ad
Related #1135

a-a-install-debuginfo: do not try to split None

---

src/plugins/abrt-dump-journal-core.c

Without this pull request, abrt-action-dump-journal-core saves coredump files uncompressed, so the problem directories are unusable.

systemd-journal core dump file fixes

---

src/hooks/abrt-hook-ccpp.c
tests/runtests/ccpp-plugin-hook-ignoring/failing_code.c
tests/runtests/ccpp-plugin-hook-ignoring/runtest.sh

ABRT will ignore crashes in executables for which absolute path matches one of
specified patterns.
Example of log messages in case of ignoring crashes:
- Crash's path is listed in 'IgnoredPath' in CCpp.conf
Process 16431 (will_segfault) of user 0 killed by SIGSEGV - ignoring
(listed in 'IgnoredPaths')
- Repeating crash
Process 16219 (will_segfault) of user 1000 killed by SIGSEGV -
ignoring (repeated crash)
- abrt-ccpp-hook crash
Process 16223 (abrt-hook-ccpp) of user 1000 killed by SIGSEGV -
ignoring (avoid recursion)
- abrt crash
Process 16228 (abrt_test) of user 1000 killed by SIGSEGV -
ignoring ('DebugLevel' == 0)
- not supported signal
Process 16229 (crash) of user 1000 killed by signal 99 - ignoring
(unsupported signal)
- abrtd is not running
Process 16229 (crash) of user 1000 killed …

RHEL7: Log that we coredump before creating the core

---

tests/runtests/mailx-reporting/runtest.sh
tests/runtests/rhts-test/runtest.sh

The test is failing if there is different locale and timezone set than on the system where the templates were generated. Thus, I'm hardcoding it to use LANG=C and timezone Europe/Prague so the date / time is generated in the same format as expected.

testsuite: mailx-reporting - hardcode locale and timezone

---

src/plugins/abrt-action-install-debuginfo.in

Also BrokenPipe error can appear even in download_class(), moving it to try
block.
Related to #1343826, #1343664

a-a-install-debuginfo: Exception may not have an argument errno

---

src/hooks/abrt-hook-ccpp.c

The calling code in abrt-install-ccpp-hook was passing in --test-config.
This was only working due to the misuse of strcmp, so it was accepting
any string other than --config-test.

abrt-hook-ccpp: Fix mismatching argument

---

doc/abrt-cli.txt
src/cli/builtin-cmd.h
src/cli/process.c
src/cli/report.c
tests/runtests/cli-process/runtest.sh
tests/runtests/cli-sanity/runtest.sh

Parameter unsafe ignores security checks and allows to report not reportable problems.
Related to #1351297
Related to #1166

Introduce unsafe reporting for not-reporable problems

---

src/daemon/abrt-server.c
src/daemon/abrtd.c

The /creation_notification method accepts arbitrary file system path and
it might cause abrtd some troubles if the path is not in canonical form.
ABRT enforces the notified paths to be directories in /var/spool/abrt
but ignores number of slash occurrences as it is not security relevant.
Switching to base names will assure that the problems associated with file
system path forms will be gone and no new problems will be introduced.
The other option is to use realpath() but this function resolves
symbolic links and if /var/spool is a symbolic link, we will be in
trouble.
Related: rhbz#1132459

RHEL7: daemon: send  base names from abrt-server to abrtd

---

src/daemon/abrt-server.c
src/hooks/abrt-hook-ccpp.c
src/hooks/abrt_exception_handler.py.in
src/hooks/abrt_exception_handler3.py.in

Requires: abrt/libreport#453
```
reason:         will_python_raise:3:<module>:ZeroDivisionError: integer division or modulo by zero
...
container: docker
container_image: fedora
...
```

abrt-addon-python in containers

---

abrt.spec.in
po/POTFILES.in
src/plugins/Makefile.am
src/plugins/abrt-action-analyze-ccpp-local.in
src/plugins/analyze_BodhiUpdates.xml.in
src/plugins/bodhi_event.conf
src/plugins/ccpp_retrace_event.conf

Analyzing of C/C++ problems should not always include finding Bodhi update - for example reporting a problem via Email does not require that. I know there were some attempts to sort out this issue in the history and I was refusing them but now I came up with an acceptable solution.
This PR introduces a new event call 'analyze_BodhiUpdates' and abrt/libreport#464 adds the event to Fedora workflows. This seems to me as the most natural approach. This approach will also enable searching for Bodhi updates for other problem types than just C/C++ problems.

Bodhi event

---

src/daemon/abrt-action-save-container-data.c
src/daemon/abrt_event.conf

strstr() returns 0 (NULL) if the needle is not found in the haystack.

a-a-s-c-data: correct detection of container type

---

tests/runtests/abrt-action-find-bodhi-update/runtest.sh
tests/runtests/ccpp-plugin-hook-ignoring/runtest.sh
tests/runtests/compat-cores/runtest.sh
tests/runtests/reporter-mantisbt/runtest.sh
tests/runtests/reporter-upload-ssh-keys/runtest.sh
tests/runtests/rhts-test/runtest.sh
tests/runtests/ureport-auth/runtest.sh

Hi,
I am currently playing around with my simple 'static analyser'-like tool that is specific for BeakerLib commands and tested it on your testsuite, so I fixed the obvious typos in command names.

testsuite: fix command typos

---

doc/abrt-action-install-debuginfo.txt
src/plugins/abrt-action-analyze-ccpp-local.in
src/plugins/abrt-action-install-debuginfo-to-abrt-cache.c
src/plugins/abrt-action-install-debuginfo.in

If we run ABRT in a container or if we catch a crash in a chroot, we
need to look for debuginfo packages relevant to the source of the crash.
Hence we need to tell package managers which version of OS we are
interested in.

ccpp: configure package repositories for correct OS

---

src/python-problem/problem/watch.py

It isn't possible to 'import gobject' if gi/gi.repository was
imported before.
---
```AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183```
This is a problem when trying to use `ProblemWatcher` from applications using `gi.repository` (so for example all Gtk applications).

Import gobject from gi.repository if gi was already imported

---

src/lib/hooklib.c

This is particularly useful when dealing with crashes in containers and
changed root environments. GDB reads the debug information from the
source elf and if the source elf is not available GDB generates useless
backtraces.

ccpp: tell gdb to analyze saved binary image

---

configure.ac
src/daemon/Makefile.am
src/daemon/rpm.c
src/daemon/rpm.h

This request is similar to the one I made for satyr, but this time the default should be yes.

daemon: Allow rpm to be optional at build time

---

src/lib/kernel.c
tests/examples/oops6.right
tests/examples/oops6.test
tests/runtests/journal-oops-processing/runtest.sh

"invalid opcode:" can be without colon.
systemd-journal output example:
traps: chrome[2979] trap invalid opcode ip:55911b28dba3 sp:7ffea558a3e0
error:0
in chrome[55911728a000+6a0b000]
Related to #1413451

kernel: modify suspicious string "invalid opcode:"

---

abrt.spec.in

If abrt is building with systemd support, the desktop vendor could be pulled out of /etc/os-release.
In theory this should eventually let the logic checking for suse/rhel/fedora fall away.
Down stream rebuilds (centos etc) should also benefit from this auto detect behavior.
https://www.freedesktop.org/software/systemd/man/os-release.html#ID=

spec: if using systemd, default to os-release ID for desktopvendor

---

src/lib/kernel.c

RHEL7: don't expect kernel's version '2.6.*' or '3.*.*' 

---

src/plugins/abrt-dump-xorg.c
tests/runtests/dumpxorg/crash_bz1328264.right
tests/runtests/dumpxorg/crash_bz1328264.test

Without this commit abrt do not records some crashes.
The messages can be prefixed by "(EE)".
Related to #1328264

RHEL7: improve parsing of journal messages

---

abrt.spec.in

In Fedora 26 is enabled systemd-coredump by default.
ABRT gets coredumps from systemd-journal instead of
changing kernel core_patern and dump core on its own.
Related to #1405995
See also: https://fedoraproject.org/wiki/Changes/coredumpctl

spec: start abrt-journal-core instead of abrt-ccpp

---

Makefile.am
abrt.spec.in

fedorahosted.org was retired on March 1st, 2017.
As we have all previous tarball created from github and all
version tags are in place I choose to use github as our new
tarball source.

Do not use fedorahosted.org for tarballs

---

src/plugins/abrt-action-check-oops-for-hw-error.in
src/plugins/koops_event.conf

Resolves abrt/abrt#1033
I think the best place to check for attempt to send MCE ureport is in
src/plugins/koops_event.conf -> EVENT=report_uReport
it would be possible in abrt-action-ureport too, but abrt-action-ureport is used by other scripts as
(ccpp_event.conf, python3_event.conf, ...) and those have nothing to do with MCEs

koops_event: add check to not send MCEs as uReports

---

src/plugins/abrt-action-check-oops-for-alt-component.in

https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior

Python 3.6 invalid escape sequence deprecation fix

---

src/lib/kernel.c
tests/Makefile.am
tests/examples/kernel_panic_oom.right
tests/examples/kernel_panic_oom.test
tests/koops-parser.at

Fixes rhbz#1439821.
Problem was, that regular kernel panic message was treated as fatal MCE, for which we don't want to have  backtrace.
The logic in koops_extract_oopses_from_lines is a bit complex, so I describe it:
If fatal MCE was recognized, dumping of backtrace was skipped by following to the next part of cycle (hacky, in the next part of cycle, there is condition with many allowed strings to continue but not "Call Trace"). The check responsible for this "jump" (kernel.c:396) just checked whether there is a string beginning with "Kernel panic - not syncing", however this string appears in all kernel panics, not just fatal MCEs.
Fatal MCE may have form of:
"Kernel panic - not syncing: Fatal Machine check" or
"Kernel panic - not syncing: Machine check" or I found even
"Kernel panic - …

Fix 1439821

---

src/daemon/abrt_event.conf
tests/runtests/dumpdir_completedness/runtest.sh
tests/runtests/oops-processing/runtest.sh

added under "remote!=1" condition, because we don't want to save cpuinfo for uploaded problems
tested for all kinds of problems, also gnome-abrt and abrt-cli list looks well, in output of "abrt-cli list --detailed" appears as:
... 
cpuinfo:        Text file, 4632 bytes
...

abrt_event: Save cpuinfo in problem directories

---

abrt.spec.in

The migration from abrt-ccpp.service to abrt-journal-core.service
has to be done only once. %{_localstatedir}/lib/abrt/abrt-migrated
file marks the migration was already done.
Some of the users want to use abrt-ccpp.service insted of
abrt-journal-core.service and we don't want to do the migration
after every abrt-addon-ccpp package updation.
Signed-off-by: mhabrnal <mhabrnal@dhcp-24-106.brq.redhat.com>

spec: migrate to abrt-journal-core only once

---

src/hooks/abrt_exception_handler.py.in
src/hooks/abrt_exception_handler3.py.in
tests/runtests/python-addon/runtest.sh
tests/runtests/python3-addon/runtest.sh

Message was modified to show command where exception happened.
$ python -c 1/0
Before:
python: detected unhandled Python exception
Now:
python: detected unhandled Python exception in 'python -c 1/0'
Related to: RHBZ#1437956

python: provide more information about exception

---

abrt.spec.in
src/daemon/Makefile.am
src/daemon/abrt_event.conf

Changing  abrt-action-save-container-data location from bin to libexec.

Abrt action save container data fix

---

src/lib/kernel.c
src/plugins/oops-utils.c

Adds detailed info about taint flags to not-reportable. This
additional info contains description of every taint flag that appeared
in particular oops.
It is either good for user information and also solves the problem when users
opened bugs on abrt from misunderstanding tainted flags.
Related to rhbz#1452160
not-reportable now looks like this (3 lines added in this case):
A kernel problem occurred, but your kernel has been tainted (flags:GW).
Taint flags description:                                             << new
G - Proprietary module has not been loaded.          << new
W - Taint on warning.                                               << new
Kernel maintainers are unable to diagnose tainted reports. Tainted modules: vboxpci,vboxnetadp,vboxnetflt,vboxdrv.

koops: Improve not-reportable for oopses with taint flags

---

src/plugins/abrt-dump-journal-core.c
tests/runtests/abrt-dump-journal-core/runtest.sh

Without this commit pid of abrt-dump-journal-core is used in a name
of created problem directory instead of pid of crashed process.
Requires https://github.com/abrt/libreport/pull/495

a-d-journal-core: use pid of crashed process in dumpdir name

---

configure.ac
src/cli/abrt-cli-core.c
src/dbus/abrt-polkit.c

This might blow your mind, but my use case for ABRT is on an embedded platform. You might have figured out by now from my pattern of pull requests that I want to be able to remove as many optional features as possible.

cli,dbus: Allow polkit to be optional at build time

---

src/daemon/abrt-handle-upload.in
src/plugins/abrt-action-find-bodhi-update
src/plugins/abrt-action-install-debuginfo.in
src/plugins/abrt-action-ureport

Some of the log() functions were omitted in commit f33b8731efedd7382e4f11d83e618a06d92a23ab.

logging: rename omitted log() to log_warning()

---

abrt.spec.in

Python 2 binary package renamed to python2-abrt
See https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3
Python 3 binary package renamed to python3-abrt
Add-on packages renamed to python[23]-abrt-addon
Documentation packages renamed to python[23]-abrt-doc

spec: rename python binary packages

---

src/cli-ng/abrt
src/cli-ng/tests/test_cli.py
src/cli-ng/tests/test_filtering.py
src/cli-ng/tests/test_match.py
src/cli-ng/tests/test_utils.py

Scripts should use /usr/bin/python[23] in shebangs.
See https://pagure.io/packaging-committee/issue/698
Also https://fedoraproject.org/wiki/Packaging:Python#Multiple_Python_Runtimes

cli-ng: Explicitly state python version in shebangs

---

src/plugins/abrt-dump-journal-core.c
tests/runtests/docker-essentials/runtest.sh

Now crashes from containers are not recognized when abrt-journal-core is running.
This PR fixes it.
It saves two now values:
1) cmdline, which later in postprocess executes abrt-action-save-container-data
2) mountinfo, which is necessary for abrt-action-save-container-data
Test would be lovely. abrt/tests/runtests/docker-essentials should be run with abrt-ccpp and abrt-journal-core as well.

Containers with journal

---

apidoc/Doxyfile.in

Removes doxygen tags XML_SCHEMA and XML_DTD in apidoc, which became
obsolete and produces warnings while doxygen documentation generation.

doc: remove obsolete doxygen tags

---

src/applet/Makefile.am
src/applet/applet.c
src/dbus/abrt_problems2_service.c
src/dbus/abrt_problems2_session.c
src/dbus/abrt_problems2_session.h

Dbus problem2 API changes must have been in flight when I made the first
patch to disable polkit. This fixes the polkit functions I missed.

dbus: Additional changes to allow optional polkit

---

abrt.spec.in

python{2,3}-gobject pulls other packages that we don't need.
python{2,3}-gobject-base is the one we want.
The pygobject is used in implementation of ProblemWatcher in python{2,3}-abrt.
Related: RHBZ#1499581

spec: change dependency on python{2,3}-gobject

---

tests/runtests/oops-processing/runtest.sh

The test oops-kernel-panic-hung-tasks-arm.test failed, because
assumed that resulting problem should be reportable, but as it contains
taint flags, it is not.

testsuite: oops-processing test fix

---

tests/runtests/reporters-home-config/PURPOSE
tests/runtests/reporters-home-config/expect
tests/runtests/reporters-home-config/runtest.sh

Tests reporter-bugzilla, reporter-rhtsupport and reporter-mantisbt
ability to use the local config, i.e. config existing in user's home.
More precisely in ~/.config/libreport/

testsuite: add tests for local config of reporters

---

abrt.spec.in

nss from version 3.35.0-3 does not require nss-pem.
Without nss-pem retrace-client was not able to initialise security
module.
Signed-off-by: Matej Marusak <mmarusak@redhat.com>

retrace-client: Require nss-pem

---

abrt.spec.in

This package uses names with ambiguous python- prefix in requirements.
According to Fedora Packaging guidelines for Python, packages must use
names with either python2- or python3- prefix in requirements where
available.
We are aiming to rename python-* dependencies to python2-*, so we can
later switch the python-* namespace to Python 3.
This PR is part of Fedora's Switch to Python 3 effort.
Note that, although this PR was created automatically, we will respond
to any comments or issues which you might find with it. We will keep the
PR open for review for a week, and if there's no feedback we'll merge
it.
Koji scratch build:
https://koji.fedoraproject.org/koji/taskinfo?taskID=23642779
Note: please do not backport this to f26 branch(es) as some of the
modified requirements are not …

spec: fix ambiguous Python 2 dependency declarations

---

abrt.spec.in
src/plugins/abrt-action-generate-machine-id

python-dmidecode is broken on aarch64 [1] and the issue won't be fixed.
Recommendation is to use regular dmidecode command instead.
The dmidecode is only available on aarch64, x86_64, i686 because
other archs (ppc, s390) do not have DMI table to decode.
Related to BZ#1569076
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1509938

plugins: a-a-g-machine-id use dmidecode command

---

abrt.spec.in

If Python2 and Python3 is allowed, require Python3 packages.
Related to #1573891

spec: requires Python3 package at first place

---

src/plugins/abrt-dump-journal-core.c

The commits of this pull request should allow image/container developers use the tool abrt-dump-journal-core to get information about crashes in their containers.
Actually, this pull request just adds the possibility to read core dump files from all systemd journals. It does that because when you run systemd in a container you have two journals:
- the host's journal
- the container's journal
Without this PR, the tool abrt-dump-journal-core reads only the latter one - the container's journal.
After merging this journal, you should be able to use the parametre "-a" to read also the host's journal where coredump files end up.
The next steps is to introduce another option to filter out all coredump files that are not from the container's hostname: …

Let containers know about their coredumps

---

abrt.spec.in
src/plugins/abrt-retrace-client.c
src/plugins/https-utils.c
src/plugins/https-utils.h

This commit removes dependency on nss-pem which is deprecated and
reimplements TLS client to use libnssckbi.so instead [1].
Resolves #1578427
[1] https://docs-old.fedoraproject.org/en-US/Fedora_Security_Team/1/html/Defensive_Coding/sect-Defensive_Coding-TLS-Client-NSS.html#ex-Defensive_Coding-TLS-NSS-Init

Remove dependency on deprecated nss-pem

---

src/hooks/abrt-hook-ccpp.c
src/hooks/abrt-install-ccpp-hook.in
tests/runtests/aux/test_order
tests/runtests/ccpp-plugin-hook/PURPOSE
tests/runtests/ccpp-plugin-hook/runtest.sh

Without this commit core_pattern's parameters %h and %e was not
translated at all.
Due to 51531e9ea72af09571688a20f00e55cad5fe9c3a, %e has to be placed
at the very end of the command in core_pattern.
Example:
If 'core_pattern = core.%h.%e.%p.%t' the result was
core.%h.sleep.26284.1469805542 not core.myshostmane.sleep.26284.1469805542.
Related to #1587891

ccpp: add %h and %e parameter into abrt-hook-ccpp

---

init-scripts/abrtd.service
tests/runtests/abrtd-directories/runtest.sh

If abrt-dbus is running and some changes are done in abrt.conf the
changes are not read and used till abrt-dbus timeouts. Timeout is set
to 133 seconds in 'dbus/org.freedesktop.problems.service'.
Killing abrt-dbus before abrtd is started forces abrt-dbus to read all
new configurations.

abrtd.service: force abrt-dbus to load changes from conf

---

src/configuration-gui/abrt-config-widget.c
src/configuration-gui/system-config-abrt.c

They are not used anymore with the current GTK3 version 3.22.x.
resolves #1310

gui-config: Remove deprecated GTK functions

---

src/lib/hooklib.c

abrt-action-generate-backtrace generates backtraces with error message:
A syntax error in expression, near `full'.
According to the GDB documentation the correct syntax for backtrace
command is:
backtrace [n]
backtrace full [n]
- sourceware.org/gdb/onlinedocs/gdb/Backtrace.html

lib: Correct the syntax for gdb backtrace command

---

src/configuration-gui/abrt-config-widget.c

g_type_class_add_private will be deprecated in Glib 2.58 [1].
There is a G_DEFINE_TYPE_WITH_PRIVATE macro that can replace
the deprecated function and it is backwards compatible [2].
[1] https://blog.gtk.org/2018/07/11/news-from-glib-2-58
[2] https://www.bassi.io/articles/2013/06/21/the-king-is-dead/

gui: Replace deprecated g_type_class_add_private

---

abrt.spec.in

The packages do not include anything that needs to be compiled/build
hence should be noarch.
Related: bz#1508511

spec: Build python*-abrt-addon packages as noarch

---

configure.ac

Check the Python3 variant of sphinx-build.

configure: Replace sphinx-build check with sphinx-build-3

---

abrt.spec.in

Turning on native-unwinder for aarch64 according to #1260074
Related to #1260074

spec: turn on --enable-native-unwinder aarch64

---

abrt.spec.in

This commit reverts changes made in commit 984758ad2fd8673d847ee83e6830845c87865808.
Together with a744f2e96c79f44a7d856f01766a933fa9b1504a these commits disabled vmcore plugin for arm64
because the kdump/kexec wasn't available on this architecture.
This changed with Fedora 26 [1] with addition of kdump support for arm64.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1387950
[2] https://www.kernel.org/doc/Documentation/kdump/kdump.txt

revert: spec: disable addon-vmcore on aarch64

---

tests/runtests/dbus-elements-handling/runtest.sh
tests/runtests/dbus-elements-handling/set_element.py

Invoking `python` inline can result in the Python 2 interpreter being
run, which might be problematic if the project was configured with
--without-python2, as the F29 test runner in particular does not have
python2-dbus installed, which is required for this test.

testsuite: dbus-element-handling: Use external script

---

tests/runtests/reporter-upload-ssh-keys/runtest.sh

With the advent of the libssh backend in curl, some of the expected
output might not be there. There is no way to check if the specified key
file is being used just by reading the output.

testsuite: reporter-upload-ssh-keys: Don’t test curl output

---

augeas/test_abrt.aug

This is a follow-up commit to the changes made in libreport:
https://github.com/abrt/libreport/pull/528/commits/5ad6d210c2fdbad88d56ae10c22a089824271392
Current lenses ignore empty comments (only '#' on the line) [1]
[1] http://augeas.net/docs/references/lenses/files/util-aug.html#Util.Comment

augeas: Adjust testsuite to changes in libreport

---

abrt.spec.in

Subpackage abrt-gui-libs, abrt-atomic consumes library libabrt.so.0()(64bit)
from subpackage abrt-libs but does not have explicit package version requirement.
Please add Requires: abrt-libs = %{version}-%{release} to abrt-gui-libs, abrt-atomic
in the specfile to avoid the need to test interoperability between the various combinations
of old and new subpackages.

spec: Add explicit package-version requirement for abrt-libs

---

src/cli/abrt-console-notification.sh
src/plugins/abrt-action-analyze-ccpp-local.in
src/plugins/abrt-action-analyze-vulnerability.in

Fixes [ShellCheck](https://github.com/koalaman/shellcheck) warnings [SC2148](https://github.com/koalaman/shellcheck/wiki/SC2148), [SC2006](https://github.com/koalaman/shellcheck/wiki/SC2006), [SC1090](https://github.com/koalaman/shellcheck/wiki/SC1090), [SC2181](https://github.com/koalaman/shellcheck/wiki/SC2181), [SC2039](https://github.com/koalaman/shellcheck/wiki/SC2039).

Fix ShellCheck warnigs reported by Covscan

---

abrt.spec.in
src/plugins/abrt-action-install-debuginfo.in

When new debuginfo packages we going to be installed check if we have
space to store them. If we don't have enough space, but we have cached
enough packages, which are not now needed, make some space.
Fixes bz#811978
Requires: https://github.com/abrt/libreport/commit/ace233e8a1ca4036fcdaa1ba645de764b9a2806f

a-a-install-debuginfo: Clean cache if we need space

---

tests/runtests/aux/pre.sh
tests/runtests/non-fatal-mce/runtest.sh

https://github.com/abrt/abrt/commit/2d1c534e8a718c673b3bf3d3005dcbac5631e5c4 should fix the spurious failures, but I can’t confirm, since the test tends to time out on consecutive runs.

Some more test fixes

---

tests/runtests/cli-process/expect
tests/runtests/cli-process/runtest.sh

RHEL builds include a uReport workflow, which gets picked up even with a
custom problem type and analyzer. This commit adds a regex to the expect
script that grabs the index of the test workflow and chooses it.

testsuite: cli-process: Guard against multiple workflows

---

src/plugins/abrt-action-install-debuginfo.in

Cleaning cache can take longer time. Users may get impatient and close
reporting. This commit informs users that the cache is being cleaned.
Also, it tests if the parent process is still alive and therefore fixes
often occurring BrokenPipeError.
Fixes BZ#1501178
Signed-off-by: Matej Marusak <mmarusak@redhat.com>

a-a-install-debuginfo: Inform user about cache being cleaned

---

src/plugins/abrt-dump-journal-xorg.c

The buffer didn't allocate enough space for terminating null
that sprintf() automatically appends after the content.

a-d-journal-core: Allocate enough space for string

---

abrt.spec.in
configure.ac
src/applet/Makefile.am
src/applet/org.freedesktop.problems.applet.service.in
src/applet/systemd/Makefile.am
src/applet/systemd/abrt-applet.service.in

Since using an autostart desktop file causes troubles on GNOME
(gnome-session chokes with D-Bus-activatable ones), having systemd
manage that instead probably makes more sense.

applet: Add systemd service unit

---

src/dbus/abrt_problems2_entry.c

When saving elements, if the file being copied exceeds size the limit,
the code will yell and bail. An issue with that is that the comparison
is not strict, which causes false positives when the actual file size is
equal to the limit.

dbus: entry: Don’t claim truncation when there was none

---

configure.ac

Since abrt-hook-ccpp requires libcap for sys/capabilities.h and the spec
file has a build-time dependency, one should be added to the autoconf
file as well.

configure.ac: Add dependency on libcap

---

src/plugins/abrt-retrace-client.c
src/plugins/analyze_RetraceServer.xml.in
tests/runtests/abrt-cli-report-mantisbt/runtest.sh

In f1d99e1d7593ab49147268b383cc82acbb0d94c1 the RETRACE_SERVER_URL was changed to RETRACE_SERVER_URI.

plugins: Fix name of env variable for retrace server

---

src/plugins/abrt-action-generate-machine-id

dmidecode can fail due to permission denies or any different reasons that
causes dmidecode to return non-zero return code.
Related: rhbz#1688368

plugins: Catch unhandled exception in a-a-g-machine-id

---

abrt.spec.in

https://bugzilla.redhat.com/show_bug.cgi?id=1686864
`abrt-dbus` requires `dbus-send` in order to function properly.

spec: Require dbus-tools

---

abrt.spec.in
augeas/abrt.aug
configure.ac
doc/abrt-CCpp.conf.txt
doc/abrt-action-save-package-data.conf.txt
doc/abrt-configuration.txt
doc/abrt-oops.conf.txt
doc/abrt-python3.conf.txt
doc/abrt-vmcore.conf.txt
doc/abrt-xorg.conf.txt
doc/abrt.conf.txt
doc/abrtd.txt
doc/dbus-configuration/com.redhat.problems.configuration.abrt.xml.in
doc/dbus-configuration/com.redhat.problems.configuration.ccpp.xml.in
doc/dbus-configuration/com.redhat.problems.configuration.oops.xml.in
doc/dbus-configuration/com.redhat.problems.configuration.python3.xml.in
doc/dbus-configuration/com.redhat.problems.configuration.vmcore.xml.in
doc/dbus-configuration/com.redhat.problems.configuration.xorg.xml.in
doc/gpg_keys.conf.txt
src/daemon/Makefile.am
src/daemon/abrt.conf
src/hooks/Makefile.am
src/lib/Makefile.am
src/lib/abrt_conf.c
src/plugins/Makefile.am
tests/abrt_conf.at
tests/runtests/dbus-configuration/runtest.sh

https://bugzilla.redhat.com/show_bug.cgi?id=1693287
All the config files were previously installed both to `/usr/share/abrt/conf.d` (defaults, loaded first), as well as `/etc/abrt` (system-wide overloads).
This PR removes the former directory and all its files and preserves the latter. Comments are also added to man pages to document where the files are located.

Remove default configuration files

---

src/plugins/abrt-action-analyze-c.c

https://bugzilla.redhat.com/show_bug.cgi?id=1708684
It seems impossible to infer the root cause of the crash from the provided coredump, so this is just a quick fix. This commit only adds a check that `frame` is not `NULL` before dereferencing it to prevent the segfault.
My hunch is that `sr_normalize_core_thread` might get rid of all the stack frames in some corner case. Though, after quickly going through the logic, I'm not sure how that would happen in real world.

a-a-analyze-c: Fix segfault when saving function name

---

src/plugins/abrt-action-list-dsos

rpm used to return bytes but that was changed to return strings in recent release.
The check for decode attribute keeps compatibility with older fedora releases.
This can be removed in the future with rpm 4.15(?)
Related: rhbz#1693751
Resolves: rhbz#1694970

a-a-list-dsos: Add check for decode attribute

---

.gitignore

This file was moved in #1403 and it was forgotten to update the path here.

Update path to generated file in .gitignore after cli-ng move

---

tests/runtests/aux/test_order
tests/runtests/skip-sosreport-dir/PURPOSE

I forgot to add the test to test-order in https://github.com/abrt/abrt/pull/1407.
The test also missed a PURPOSE description.

testsuite: Minor fixes for skip-sosreport-dir test

---

src/cli/abrtcli/l18n.py
src/daemon/abrt-handle-upload.in
src/plugins/abrt-action-analyze-core.in
src/plugins/abrt-action-analyze-vmcore.in
src/plugins/abrt-action-check-oops-for-alt-component.in
src/plugins/abrt-action-check-oops-for-hw-error.in
src/plugins/abrt-action-install-debuginfo.in
src/plugins/abrt-action-perform-ccpp-analysis.in
src/plugins/abrt-action-ureport
src/plugins/abrt-gdb-exploitable

6cac02cec6f457e4ab4edca8cebe2cda8dc4061d removed uses of l*gettext(),
which are the target of bind_textdomain_codeset(), thus making it no
longer needed.
Fixes https://github.com/abrt/abrt/issues/1411

Drop uses of bind_textdomain_codeset()

---

src/cli/abrtcli/cli.py
src/cli/abrtcli/match.py
src/cli/tests/test_match.py

This commit does several things:
* Adds a hardcoded “*” pattern for bulk processing
* Replaces hardcoded “last” pattern with nothing, so that the last
problem is the default
* Adds path resolution to allow things like relative paths (trailing
slash no longer an issue as well)
* As a side effect, makes matching against component return all
problems, as opposed to complaining about ambiguity
Related: https://github.com/abrt/abrt/issues/1394
Fixes https://github.com/abrt/abrt/issues/1389
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1329711
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1329712

cli: Tweak problem matching

---

abrt.spec.in

In the process, also fix rpmlint warnings and escape macros in comments.

spec: Use macros where appropriate

---

abrt.spec.in
src/cli/abrtcli/Makefile.am
src/cli/abrtcli/cli/Makefile.am
src/hooks/Makefile.am

According to the [packaging guide](https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_macros), we should be using `%{python3_sitelib}` to install Python modules rather than `%{python3_sitearch}` which is more suitable for compiled extensions. This also needs to be reflected in the automake scripts, where we need to replace `$(pyexecdir)` with `$(pythondir)`. (See [automake manual](https://www.gnu.org/software/automake/manual/html_node/Python.html).)
This is a follow-up to 20dcf7fb4.

Use correct paths for installed Python modules

---

src/daemon/abrt_event.conf
src/plugins/koops_event.conf
src/plugins/vmcore_event.conf

Even though libreport should parse the hanging lines as separate from
the preceding event, let's be on the safe side with these.

events: Comment examples consistently

---

src/dbus/abrt_problems2_service.c
src/plugins/abrt-action-analyze-backtrace.c
src/plugins/abrt-action-analyze-c.c
src/plugins/abrt-action-analyze-python.c

d605ffeaa6ae411ef396160ffd67b7a6fd27c6ba in libreport removed some
convenience API for hashing data, so let’s just go with what GLib has in
store.

Use GChecksum to compute checksums

---

src/include/libabrt.h
src/lib/kernel.c
src/plugins/abrt-action-analyze-oops.c
tests/koops-parser.at

Change the API so that `koops_hash_str` and `koops_hash_str_ext` return the heap-allocated encoded digest instead of taking a pointer and returning a status code.
This eliminates the need to know the size of the resulting hash in advance, which should solve the build problems following recent libreport changes.

koops: Avoid explicit dependency on hash size

---

src/dbus/abrt_problems2_service.c

While enumerating all the problems in itself might not be too slow,
requesting properties for each *will* be slow. This commit adds a
warning to the user that a cleanup might be in order.

dbus: Warn about large number of problems

---

abrt.spec.in
src/plugins/Makefile.am
src/plugins/abrt_ccpp.catalog.in
src/plugins/catalog_journal_ccpp_format.conf
tests/runtests/reporter-systemd-journal/runtest.sh

abrt_ccpp.catalog was accidently deleted in #1419 
and ...
Short backtrace was missing in journal catalog messages.
In case of will_stackoverflow:
```
-- #1 [will_stackoverflow] f
-- #2 [will_stackoverflow] main
```

Make CCpp journal catalog messages great again 

---

src/plugins/bodhi.c

During a rebuilt on s390x this error came up:
```
bodhi.c:340:12:
error:
'unstable_karma' may be used uninitialized in this function
```

bodhi: Initialize karma values with default

---

abrt.spec.in

New libreport changes are incompatible with older abrt releases.

spec: bump reqired libreport version

---

abrt.spec.in

Since /var/run is typically symlinked to /run, which is mounted as tmpfs, the directory will disappear after a reboot if abrtd.service is disabled. Adding a %ghost directive makes sure that RPM verification succeeds even if the directory had been nuked.
https://bugzilla.redhat.com/show_bug.cgi?id=1805728

spec: Add %ghost for /var/run/abrt

---

src/lib/hooklib.c
src/plugins/abrt-action-analyze-core.in
src/plugins/abrt-action-install-debuginfo.in

A change was introduced in Fedora 27 to allow for installing multiple versions of debuginfo packages in parallel. In effect, `/usr/lib/.build-id` may contain debug files as well in addition to `/usr/lib/debug/.build-id`.
See https://fedoraproject.org/wiki/Changes/ParallelInstallableDebuginfo for more details.
Follow-up to abrt/faf#851 and abrt/libreport#606.

Accomodate for multiple debug directories

---

src/cli/abrtcli/config.py.in

Forgot about this little bugger here.
Follow-up to 8ebe0be1.

cli: Correct debug directories in config

---

src/plugins/abrt-dump-journal-core.c
src/plugins/abrt-journal.c
src/plugins/abrt-journal.h

Sure, maybe glibc defines uid_t as a uint32_t, but POSIX does not impose
any limits on the underlying type, so let’s just accept whatever systemd
gives us. If what systemd gives us is non-compliant, then we are already
in trouble and it makes no sense to defend against nasal demons.
Moreover, using a long for bounds and passing UINT_MAX is just asking
for trouble (i.e. it fails on 32-bit systems).

plugins: abrt-journal-core: Don’t assume anything about uid_t

---

abrt.spec.in
configure.ac

No longer needed after 77653d7a367a756e796f5b820d9bea3c8feb117e.

Drop libcap dependency

---

src/plugins/abrt-dump-journal-core.c
src/plugins/abrt-journal.c
src/plugins/abrt-journal.h

Builds on top of 98c4205a717dbca34c3a889c6c133ed06feb335f, which was a
horrible mess. In systems that use the LP64 data model (Linux), writing
to ci_pid in struct crash_info through a long pointer would result in
ci_mapping being overwritten, leading to crashes when collecting core
dumps from the journal. This commit address the original issue in a
different - several wrappers are provided for a macro that casts the
result from strtol() to a suitable type. The potential issue with
insufficient range or unexpectedly negative numbers is left unaddressed,
as that would only happen in cases of journal corruption, so it is
likely that the problem directory would contain a bunch of garbage
anyway.

plugins: journal: Fix ci_mapping being overwritten

---

src/plugins/abrt-action-analyze-core.in
src/plugins/abrt-action-install-debuginfo.in

Revert erroneous changes from a349b2c7cb26a3cddb673dd8e62455f17016ad15

Remove libreport_ namespace from python code

---

Makefile.am

`$ make release-{major|minor|bug}` creates a new empty entry in CHANGELOG.md
but commits the change before the user has a chance to fill it, making
it necessary to amend and re-tag the release commit. This commit opens
an editor to let the user edit the changelog in time.

Allow editing CHANGELOG.md before release commit

---

src/daemon/abrtd.c
src/include/libabrt.h
src/lib/hooklib.c
src/plugins/abrt-action-generate-backtrace.c
src/plugins/abrt-action-generate-core-backtrace.c

See commits.  
Resolves https://github.com/abrt/abrt/issues/1357  
See also https://github.com/abrt/libreport/pull/629

Keep problem dirs locked while (core) backtrace is being generated

---

src/hooks/abrt_harvest_vmcore.py.in

python3.8 raises SyntaxWarning when comparing literals using `is` and it appears in `systemctl status abrt-vmcore`

abrt-vmcore: Fix SyntaxWarning with python3.8

---

src/plugins/sosreport_event.conf

The "startup" plugin was renamed to "services" a long time ago:
https://github.com/sosreport/sos/commit/b502b9f51b4d314ed6fa76d66a6db8aea7d32c12  
See also: `sosreport -l`

sosreport_event: Update plugin name

---

src/dbus/abrt_problems2_entry.c
src/dbus/abrt_problems2_service.c

Take over #1421.
Rebased onto master and changed return value of `abrt_p2_entry_get_owner` to 0 (`uid_t` may be unsigned).
Depends on abrt/libreport#630

dbus: Update dd_get_owner

---

src/plugins/analyze_CCpp.xml.in
src/plugins/analyze_LocalGDB.xml.in
src/plugins/analyze_RetraceServer.xml.in
src/plugins/analyze_VMcore.xml.in
src/plugins/collect_GConf.xml.in
src/plugins/collect_vimrc_system.xml.in
src/plugins/collect_vimrc_user.xml.in
src/plugins/collect_xsession_errors.xml.in
tests/runtests/localized-reporting/test_event_lr.xml
tests/runtests/verify-that-report-edits/test_event_vtre.xml

The information is not used anywhere in libreport (anymore).
See https://github.com/abrt/libreport/pull/623.

Drop creates-items tag from event definitions

---

HACKING.md
doc/abrt-retrace-client.txt
doc/implementation
doc/plugins-howto
src/dbus/abrt_polkit.policy
src/plugins/analyze_RetraceServer.xml.in
src/python-problem/doc/index.rst
tests/helpers/docs/index.rst
tests/helpers/test_beaker_f15.xml
tests/runtests/abrt-make-check/runtest.sh
tests/runtests/abrt-nightly-build/runtest.sh
tests/runtests/btparser-make-check/runtest.sh
tests/runtests/libreport-make-check/runtest.sh

fedorahosted.org has been partially decomissioned, but
some of our links were still pointing to it. Unfortunatelly
some of the pages were not migraated, so there is not always
a new alternative so the text was slightly modified in
some cases.
Resolves:
https://github.com/abrt/abrt/issues/1251

doc: Remove or replace some fedorahosted links

---

src/daemon/abrt-action-save-package-data.c
src/daemon/rpm.c
src/daemon/rpm.h

libdnf is only able to parse package names in the NEVRA form, leading to
retrace-server bailing when retracing dumps from, say, gedit.
Closes https://github.com/abrt/abrt/issues/1378
Fixes https://github.com/abrt/retrace-server/issues/233

daemon: rpm: Use NEVRA instead of ENVRA

---

init-scripts/abrt.conf

This commit adds /var/cache/abrt-di and /var/run/abrt to the
systemd-tmpfiles config for automatic creation and, should the user want
it, timed cleanup.
Closes https://github.com/abrt/abrt/issues/1366

init-scripts: Add directories to systemd-tmpfiles config

---

src/daemon/abrt-server.c

Fallout from 89e0ddda. `g_autofree`'d `dup_of_dir` would get `free`'d in the
`RESPONSE_SETTER` macro and it was getting reassigned with `g_strdup` inside
a loop anyway.

abrt-server: Fix double free and possible leaks

---

.github/workflows/check.yml

So that we can get rid of the Jenkins job that is only accessible
within the Red Hat intranet.

Add GitHub Actions workflow for building PRs

---

src/plugins/abrt-dump-journal-core.c

Since v246-rc1, systemd supports zstd-compressed objects, which
definitely includes core dumps. This commit adds another check,
alongside .lz4 and .xz extensions in COREDUMP_FILENAME.

plugins: abrt-dump-journal-core: Handle zstd compression

---

src/plugins/oops-utils.c

Originally, the only effect of the `ABRT_OOPS_WORLD_READABLE` flag was to store the owner in the metadata directory as 'nobody'.
This commit reflects the flag in the filesystem permissions as well by allowing world to read the directory or, in chmod symbolic language, setting the mode to `o+r`.
Resolves #1515

oops-utils: Respect the 'world-readable' flag

---

abrt.spec.in

Koji builds fail because:
It's not recommended to have unversioned Obsoletes
It's not recommended to use '>' in Obsoletes

spec: Fix Obsoletes

---

tests/runtests/upload-handling/runtest.sh

Just in case someone messes up so royally and we end up running
`rm -rf /`.

tests: upload-handling: Quote paths more liberally

---

src/plugins/abrt-action-install-debuginfo.in

Only print the number of debuginfo packages to be installed once we know the precise number, i.e. do not show how many debuginfo files are "missing".
Depends on abrt/libreport#671
Resolves #1514

a-a-install-debuginfo: Correct debuginfo numbers

---

src/lib/hooklib.c

The result of abrt_get_backtrace was being freed every time, even when
no error occured.
Resolves:
https://github.com/abrt/abrt/issues/1528
https://bugzilla.redhat.com/show_bug.cgi?id=1881745

hooklib: Don't g_autofree backtrace

---

src/lib/hooklib.c

Improper bracing caused the `bt` variable to be freed every time in every iteration no matter what. This would then lead to an invalid (freed) pointer being returned by the function.
The mistake was made in 1f2963b0 and [reported](https://bugzilla.redhat.com/show_bug.cgi?id=1881745) by Jeff Law.

hooklib: Proper freeing of backtrace

---

src/daemon/abrtd.c

A `goto` jump over a pointer declaration with `g_autofree` causes an
invalid free at end of scope.
Resolves:
https://bugzilla.redhat.com/show_bug.cgi?id=1895660

abrtd: Don't jump over g_autofree

---

tests/Makefile.am
tests/koops-parser.at

Just tweak valgrind setup a bit and fix a few minor memory issues in tests. More errors that were popping up in the ABRT testsuite originated in Satyr code and were fixed in https://github.com/abrt/satyr/pull/310

tests: Fix leaks

---

CHANGELOG.md
src/daemon/rpm.c

The string format was changed in 7013e4e to the correct NEVRA form used by libdnf, but it was somehow botched by changes in 7e7cc101.
Resolves [rhbz#1900982](https://bugzilla.redhat.com/show_bug.cgi?id=1900982)

rpm: Correct NEVRA format

---

src/plugins/abrt-retrace-client.c

This should help debugging some retrace server issues. In particular, we should be able to traces server failures back to a particular retrace task, which is near impossible right now.

Output task ID in retrace-client console

---

.github/workflows/coverity.yml

Are you tired of getting failure emails every weekend? Don’t answer that - a rhetorical question.
Then this is for you!
With the changes, the workflow itself finishes and can be triggered manually, but there is still the problem of Coverity Scan not supporting GCC 10 (though I forget the details now, but I recall complaining to them about some header-parsing thing). That one might take a year or two before they release a fixed-up version, given their cadence so far.

Fix Coverity workflow

---

CHANGELOG.md
src/cli/abrtcli/cli/report.py

Handle a previously unhandled exception which would crash abrt-cli in the corner case of the problem directory disappearing mid-reporting.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1914583

cli: Gracefully handle disappearance of problem directory

---

CHANGELOG.md
abrt.spec.in
src/hooks/abrt_exception_handler3.py.in

`abrt-action-check-oops-for-hw-error` from the abrt-addon-vmcore package imports `systemd.journal` but the python3-systemd package is not declared as a dependency, which causes the script to crash if python3-systemd is not installed on the system.
This commit fixes this by adding the formal dependency in the spec file.
Resolves [rhbz#1914170](https://bugzilla.redhat.com/show_bug.cgi?id=1914170)

Add dependency on python3-systemd for abrt-addon-vmcore

---

abrt.spec.in

Those comments caused syntax warning while running ./autogen.sh sysdeps on up-to-date Fedora 33.
> warning: extra tokens at the end of %endif directive in line 82:  %endif # with python3
>
> warning: extra tokens at the end of %endif directive in line 100:  %endif # with python3
> 
> warning: extra tokens at the end of %endif directive in line 133:  %endif # with python3
> 
> warning: extra tokens at the end of %endif directive in line 198:  %endif # with python3
> 
> warning: extra tokens at the end of %endif directive in line 259:  %endif # with python3
> 
> warning: extra tokens at the end of %endif directive in line 308:  %endif # with python3
> 
> warning: extra tokens at the end of %endif directive in line 331:  %endif # with python3
> 
> warning: extra tokens at the end of %endif …

Removed comments in abrt.spec.in after %endif

---

abrt.spec

as asked in https://src.fedoraproject.org/rpms/abrt/pull-request/12

Obsoletes abrt-plugin-sosreport, to fix upgrade path

---

src/plugins/abrt-action-analyze-oops.c

Fixes issue #1563
This doesn't change the corresponding `msgid` in the po files, but in a comment on the issue someone remarked
>  You don't have to deal with the .po files

change obscure "signalize" to "indicate" in string

---

src/daemon/abrt-action-save-container-data.c
src/daemon/abrt-handle-event.c
src/daemon/abrt-upload-watch.c
src/daemon/rpm.c
src/dbus/abrt_problems2_service.c
src/dbus/abrt_problems2_session.c
src/lib/hooklib.c
src/lib/kernel.c
src/plugins/abrt-dump-journal-core.c
src/plugins/abrt-dump-journal-oops.c
src/plugins/abrt-journal.c
src/plugins/abrt-retrace-client.c
src/plugins/bodhi.c
src/plugins/xorg-utils.c

There are a number of places where memory was allocated with a glib2
function and then freed with the glibc free function. This patch
corrects the mismatch so that memory allocated by glib2 is freed by
glib2.

Fix mismatched allocation / free

---

src/daemon/abrt-action-save-package-data.c
src/plugins/abrt-retrace-client.c
src/plugins/xorg-utils.c

get_script_name allocates memory to script_pkg which must be freed.
If we assign script_pkg to pkg_name, then when it goes to ret, it
will call free_pkg_nevra on the memory to free it.
g_build_filename allocates memory to path that must be freed.
get_settings allocates memory to settings that must be freed
g_strdup allocates memory to exe. If it is not added to crash_info,
the it must be freed.

Fix a few memory leaks

---

src/include/libabrt.h
src/lib/hooklib.c
src/lib/libabrt.sym
src/plugins/abrt-action-generate-backtrace.c
src/plugins/abrt-action-generate-core-backtrace.c
src/plugins/abrt-dump-journal-core.c

This PR moves the coredump retrieval to a later stage of the problem dir creation, namely by integrating it into `abrt-action-generate-backtrace` and `abrt-action-generate-core-backtrace`. The coredump is retrieved by calling `coredumpctl` directly, rather than by using `sd_journal_get_data`.

Use coredumpctl to retrieve coredump

---

CHANGELOG.md
src/hooks/abrt_exception_handler3.py.in

The abrt_exception_handler3 module is always imported when Python starts,
but all the modules imported from it (except sys) are only used during crashes.
Especially the systemd.journal import is really expensive.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2007664

Use lazy imports in abrt_exception_handler3

---

tests/runtests/dbus-problems2-sanity/cases/abrt_p2_testing/__init__.py
tests/runtests/dbus-problems2-sanity/cases/test_concurency.py
tests/runtests/dbus-problems2-sanity/cases/test_get_problem_data.py
tests/runtests/dbus-problems2-sanity/cases/test_get_problems.py
tests/runtests/dbus-problems2-sanity/cases/test_new_problem.py
tests/runtests/dbus-problems2-sanity/cases/test_problem_entry_properties.py
tests/runtests/dbus-problems2-sanity/cases/test_session_get_authorize_close.py
tests/runtests/dbus-problems2-sanity/cases/test_session_limits.py

The methods `assert(Not)?Equals()` and `assertRegexpMatches()` have been deprecated since Python 3.2 and were removed in Python 3.11.

tests: Fix calls to deprecated methods

---

CHANGELOG.md
src/plugins/abrt-journal.c

abrt-dump-journal-xorg and abrt-dump-journal-oops die when they
encounter a corrupt journal file. This makes restarting their
respective daemons impossible because the program crashes before it has
a chance to set and save its journal read cursor past the corrupt data.
This commit makes the programs go on with just a warning so there's an
opportunity to save the read cursor and thus recover from the condition.
This only affects abrt-dump-journal-xorg and abrt-dump-journal-oops when
run in the follow/daemon mode (i.e. with the -f option).
Resolves:
https://bugzilla.redhat.com/show_bug.cgi?id=1433652
https://bugzilla.redhat.com/show_bug.cgi?id=2043495

abrt-dump-journal: Don't die on corrupt data

---

CHANGELOG.md
src/include/libabrt.h
src/lib/hooklib.c
src/lib/libabrt.sym
src/plugins/abrt-action-generate-backtrace.c
src/plugins/abrt-action-generate-core-backtrace.c
src/plugins/abrt-dump-journal-core.c

This is the easiest way for now. Otherwise we would need to make sure that the SELinux problems are fixed not just in Fedora, but in other channels as well.

Revert coredump retrieval optimization patches (rhbz#2052872)

---

CHANGELOG.md
src/plugins/abrt-dump-journal-oops.c

See: https://github.com/abrt/abrt/issues/1604
The service would not start if the cursor state file was missing or invalid.
With this patch, the service will simply start following journal from the end.

abrt-oops: Follow journal from the end if the position cannot be restored

---

src/daemon/rpm.c

`pgpHexStr()` function has been deprecated and renamed to `rpmhex()`.
Since the replacement is only available in Rawhide (f37), let's
continue using the old name for now.
This commit tells gcc to ignore the deprecation warning.
See the commit:
https://github.com/rpm-software-management/rpm/commit/d44be2cbc1c3265d55f05b47daa69334a7a133e6

Fix for rpm 4.18

---

abrt.spec

Not sure what the %{desktopvendor} macro does but if undefined, it
doesn't expand to anything without the '?', meaning the condition is
never true.

spec: Fix macro expansion

---

src/lib/hooklib.c
src/plugins/abrt-dump-journal-core.c

Use the appropriate standard type for timestamps instead of just `int` or `unsigned` in order to prevent any possible headaches down the road.
Problem reported by Coverity.

lib: Use time_t for timestamps

---

abrt.spec
src/cli/Makefile.am
src/cli/abrt
src/cli/abrt.bash_completion

Advertise support for argcomplete global completion. [1]
Remove the abrt specific bash completion script.
The bash completion script from python3-argcomplete in
`/etc/bash_completion.d/python-argcomplete`
will do the completion for `abrt`.
This change avoids the bash startup calling `register-python-argcomplete abrt`,
which takes some time.
[1]: https://github.com/kislyuk/argcomplete#global-completion

cli: use python3-argcomplete global completion

---

.github/workflows/check.yml
.github/workflows/coverity.yml
src/plugins/abrt-journal.c

See: rhbz#2128662
Under certain circumstances, abrt-dump-journal can be running, but not receiving any event notifications from journal.
The culprit of the issue seems to be the delayed call to sd_journal_get_fd(), as discussed in various
issues and pull-requests in other projects.
See for example [1], [2], or [3].
[1]: https://github.com/systemd/systemd/issues/7998
[2]: https://github.com/ledbettj/systemd-journal/pull/78
[3]: https://github.com/rsyslog/rsyslog/issues/2436

abrt-journal: call sd_journal_get_fd() right after sd_journal_open()

---

src/plugins/abrt-dump-journal-core.c

See: rhbz#2128662
a-dump-journal-core uses filters to jump between
systemd-coredump entries in journal.
However, we should first jump to the starting position (journal tail) and only then set filters.
I suspect that setting the filters early, before we are at the starting position, can lead to the strange
behavior that we are seeing in Fedora.
This patch makes the problem go away on my freshly-installed Fedora 37 VM.

a-dump-journal-core: First seek the journal tail and then set filters

---

README.md

Use the native Mermaid.js integration in GitHub Markdown to display a clickable diagram of related repositories, i.e. the relevant repos in the abrt organization.

readme: Add diagram of related projects

---

src/daemon/rpm.c

In RPM 4.19, the pgpHexStr() function was renamed to rpmhex(), much like
the comment here in the code suggests.  The function was deprecated in
RPM 4.18 while keeping the original shim.  That's no longer the case in
4.19, though, where it was removed.
Now that Fedora 38 is the latest stable release and Fedora 39 is getting
RPM 4.19, it's probably time to finally make the move.

Replace now gone pgpHexStr() with rpmhex()

---

src/lib/check_recent_crash_file.c

Limit executable name length to 2048 characters (an arbitrary number, should be large enough for any practical purpose).
Fixes #1638

lib: Fix ‘read size exceeds maximum object’ error

---

init-scripts/abrtd.service

ABRT no longer uses /var/tmp/abrt/ for storing problem data. Therefore we are not concerned about livesys re-mounting /var/tmp/ as tmpfs and thus hiding it from abrtd.
Fixes: rhbz#2171200

abrtd: remove livesys.service reference from the systemd unit file

---

abrt.spec

This issue was reported by rpminspect:
"""
Subpackage abrt-plugin-bodhi on x86_64 carries 'Requires: libabrt.so.0()(64bit)' which comes from subpackage abrt-libs but does not carry an explicit package version requirement.
"""

spec: plugin-bodhi requires abrt-libs

---

src/plugins/ccpp_event.conf

Related: gh#1656
ureport works with the core backtrace retrieved from coredumpctl, but the backtrace is sometimes quite useless:
Stack trace of thread 3219:
#0  0x0000aaaaca9d02dc crash.constprop.0 (will_segfault + 0x102dc)
#1  0x0070aaaaca9d0370 n/a (n/a + 0x0)
...
#9  0x0013ffff8dd40abc n/a (n/a + 0x0)
#10 0x0076aaaaca9d0170 n/a (n/a + 0x0)
ELF object binary architecture: AARCH64
abrt (understadably) complains about such low value backtrace and refuses to continue. However, when we later run gdb on the coredump, we actually get a good backtrace out of it.
This commit makes ureport failures non-blocking and thus there is a chance that we will get a good quality backtrace from gdb later.

ccpp: don't fail bug reporting on ureport failure

---

CHANGELOG.md
src/dbus/abrt-dbus.c

Fixed typo in src/dbus/abrt-dbus.c

Fix typo in dbus error message

---

abrt.spec
src/daemon/rpm.c

The old way doesn't work with RPM 6.0.0.
Related: rhbz#2396899

Use rpmPubkeyKeyIDAsHex() to obtain the gpg key in hex format
